version: '3'
services:
  configuration-server:
    image: config-server-image
    hostname: config-server-microservice
    ports:
      - "8888:8888"
    networks:
      - my-network

  registration-server:
    image: eureka-server-image
    hostname: eureka-server
    ports:
      - "8761:8761"
    networks:
      - my-network

networks:
  my-network:
