spring:
    datasource:
        url: "jdbc:h2:mem:humidityDB"
    h2:
        console:
            enabled: true
    application:
        name: humidity-microservice

server:
    port: 8090

eureka:
    client:
        service-url:
            defaultZone: http://192.168.56.1:8761/eureka/
    instance:
        preferIpAddress: true