spring:
  datasource:
    url: "jdbc:h2:mem:temperatureDB"
  h2:
    console:
      enabled: true
  application:
    name: temperature-microservice

server:
  port: 8091

eureka:
  client:
    service-url:
        defaultZone: "http://192.168.56.1:8761/eureka/"
  instance:
    preferIpAddress: true
